apiVersion: v1
kind: Pod
metadata:
  name: neo-pod
  labels:
    name: neo-pod
spec:
  containers:
  - name: neo-pod-ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"