apiVersion: v1
kind: Pod
metadata:
  name: trinity-pod
spec:
  containers:
  - name: trinity-pod-ctr
    image: redis
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"